version: "2"

services:

    flask:
        build: ./flask
        container_name: flask
        restart: always
        expose:
            - 8080

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        depends_on:
        - flask
        - nextjs

    nextjs:
        build: ./nextjs
        container_name: nextjs
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - flask